# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e3ec2479afd93b56bbd00ab898c0661"
application_url = "https://as-recently-shirts-greece.trycloudflare.com"
embedded = true
name = "wishlist"
handle = "wishlist-665"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://as-recently-shirts-greece.trycloudflare.com/auth/callback",
  "https://as-recently-shirts-greece.trycloudflare.com/auth/shopify/callback",
  "https://as-recently-shirts-greece.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "boostmyappetitestore.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
